// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: replication/proto/replication.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamWALRequest is sent by the follower to initiate replication.
type StreamWALRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// from_lsn is the first LSN the follower wants. Typically appliedLSN + 1.
	FromLsn uint64 `protobuf:"varint,1,opt,name=from_lsn,json=fromLsn,proto3" json:"from_lsn,omitempty"`
	// follower_id is an opaque identifier for logging/diagnostics.
	FollowerId    string `protobuf:"bytes,2,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamWALRequest) Reset() {
	*x = StreamWALRequest{}
	mi := &file_replication_proto_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamWALRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWALRequest) ProtoMessage() {}

func (x *StreamWALRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWALRequest.ProtoReflect.Descriptor instead.
func (*StreamWALRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{0}
}

func (x *StreamWALRequest) GetFromLsn() uint64 {
	if x != nil {
		return x.FromLsn
	}
	return 0
}

func (x *StreamWALRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

// WALEntryProto is a single WAL entry shipped over the wire.
// The payload is the raw msgpack-encoded operation data — the follower
// deserialises it using the same WALEntry codec as the leader.
type WALEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lsn           uint64                 `protobuf:"varint,1,opt,name=lsn,proto3" json:"lsn,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Op            uint32                 `protobuf:"varint,3,opt,name=op,proto3" json:"op,omitempty"`          // OpType enum value
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // msgpack-encoded operation payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALEntryProto) Reset() {
	*x = WALEntryProto{}
	mi := &file_replication_proto_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALEntryProto) ProtoMessage() {}

func (x *WALEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALEntryProto.ProtoReflect.Descriptor instead.
func (*WALEntryProto) Descriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{1}
}

func (x *WALEntryProto) GetLsn() uint64 {
	if x != nil {
		return x.Lsn
	}
	return 0
}

func (x *WALEntryProto) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *WALEntryProto) GetOp() uint32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *WALEntryProto) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_replication_proto_replication_proto protoreflect.FileDescriptor

const file_replication_proto_replication_proto_rawDesc = "" +
	"\n" +
	"#replication/proto/replication.proto\x12\vreplication\"N\n" +
	"\x10StreamWALRequest\x12\x19\n" +
	"\bfrom_lsn\x18\x01 \x01(\x04R\afromLsn\x12\x1f\n" +
	"\vfollower_id\x18\x02 \x01(\tR\n" +
	"followerId\"n\n" +
	"\rWALEntryProto\x12\x10\n" +
	"\x03lsn\x18\x01 \x01(\x04R\x03lsn\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\rR\x02op\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload2^\n" +
	"\x12ReplicationService\x12H\n" +
	"\tStreamWAL\x12\x1d.replication.StreamWALRequest\x1a\x1a.replication.WALEntryProto0\x01B0Z.github.com/mstrYoda/goraphdb/replication/protob\x06proto3"

var (
	file_replication_proto_replication_proto_rawDescOnce sync.Once
	file_replication_proto_replication_proto_rawDescData []byte
)

func file_replication_proto_replication_proto_rawDescGZIP() []byte {
	file_replication_proto_replication_proto_rawDescOnce.Do(func() {
		file_replication_proto_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replication_proto_replication_proto_rawDesc), len(file_replication_proto_replication_proto_rawDesc)))
	})
	return file_replication_proto_replication_proto_rawDescData
}

var file_replication_proto_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_replication_proto_replication_proto_goTypes = []any{
	(*StreamWALRequest)(nil), // 0: replication.StreamWALRequest
	(*WALEntryProto)(nil),    // 1: replication.WALEntryProto
}
var file_replication_proto_replication_proto_depIdxs = []int32{
	0, // 0: replication.ReplicationService.StreamWAL:input_type -> replication.StreamWALRequest
	1, // 1: replication.ReplicationService.StreamWAL:output_type -> replication.WALEntryProto
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_replication_proto_replication_proto_init() }
func file_replication_proto_replication_proto_init() {
	if File_replication_proto_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replication_proto_replication_proto_rawDesc), len(file_replication_proto_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replication_proto_replication_proto_goTypes,
		DependencyIndexes: file_replication_proto_replication_proto_depIdxs,
		MessageInfos:      file_replication_proto_replication_proto_msgTypes,
	}.Build()
	File_replication_proto_replication_proto = out.File
	file_replication_proto_replication_proto_goTypes = nil
	file_replication_proto_replication_proto_depIdxs = nil
}
